name: executer_tests_unitaires_quand_push_sur_une_branche
on:
  push
jobs:
    tests:
      name: Exécuter les tests JUnit
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
        - uses: actions/checkout@v2

        - name: Set up JDK 17
        - uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: mvn test
        - run: mvn -B test --file pom.xml