name: executer_tests_unitaires_quand_push_sur_une_branche
on:
  push
jobs:
    tests:
      name: Exécuter les tests JUnit
      runs-on: ubuntu-latest
      with:
        uses: actions/setup-java@v1
        java-version: 17
      steps:
        - name: mvn test
        - run: mvn test