name: executer_tests_unitaires_quand_push_sur_une_branche
on:
  push
jobs:
    tests:
      name: Exécuter les tests JUnit
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Checkout

        - name: JDK
        - uses: actions/setup-java@v1
          with:
            java-version: '21'
            distribution: 'openjdk'

        - name: build
          run: mvn -B package --file pom.xml

        - name: test
          run: mvn -B test --file pom.xml
        - name: report
          uses: mikepenz/action-junit-report@v2
          if: always()
          with:
            name: JUnit Report
            path: 'target/surefire-reports/TEST-*.xml'
            reporter: 'GitHub Actions'
            fail_on_error: false