name: executer_tests_unitaires_quand_push_sur_une_branche
on:
  push
jobs:
    tests:
      name: Exécuter les tests JUnit
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
        - uses: actions/checkout@v3

        - name: mvn test
          run: mvn test